BlogSite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_view
from blogapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('register/',views.registration,name='register'),
    path('post/',include('blogapp.urls')),
    path('login/', auth_view.LoginView.as_view(),name='login'),
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),
]

blogapp/urls.py
from django.urls import path
from blogapp import views

app_name = 'blogapp'

urlpatterns = [

    path('create/',views.createpost.as_view(),name='createpost'),
    path('list/',views.post_list.as_view(),name='post_list'),
    path('draft_list/',views.draft_list.as_view(),name='draft_list'),
    path('detail/<int:pk>',views.PostDetail.as_view(),name='post_detail'),
    path('draftpost/<int:pid>',views.draftpost,name='draft_post'),
    path('draftdetail/<int:pk>',views.DraftDetail.as_view(),name='draft_detail'),
    path('edit/<int:pk>',views.UpdatePost.as_view(),name='editpost'),
    path('delete/<int:pk>',views.PostDelete.as_view(),name='deletepost'),
    path('comment/<int:cid>',views.CreateComment,name='comment'),
    path('editcomment/<int:cid>',views.editcomment,name='edit_comment'),
    path('deletecomment/<int:cid>',views.delete_comment,name='delete_comment'),
]

blogapp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('blogapp:post_detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('Post',on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('blogapp:post_list')

    def __str__(self):
        return self.text

blogapp/forms.py
from blogapp.models import Post
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
class PostForm(forms.ModelForm):
    class Meta:
        fields = ('title','text')
        model = Post
        widgets = {
        'title': forms.TextInput(attrs={'class':'form-control','id':'fortitle'}),
        'text': forms.Textarea(attrs={'class':'form-control','id':'fortext'}),
        }

blogapp/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from blogapp.models import Post,Comment
from django.urls import reverse_lazy,reverse
from blogapp.forms import PostForm
from django.contrib.auth.models import User
from django.utils import timezone
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User


def home(request):
    if request.user.is_authenticated:
        post_list = Post.objects.filter(published_date__isnull = False).filter(author=request.user).order_by('-id')
        return render(request,'blogapp/home.html',context={'post_list':post_list})
    else:
        return render(request,'blogapp/home.html')

def registration(request):
    if request.method == 'POST':
        name = request.POST.get('username')
        pwd1 = request.POST.get('password1')
        pwd2 = request.POST.get('password2')
        if pwd1 == pwd2:
            user_check = User.objects.get_or_create(username=name)
            if user_check[1] == False:
                return render(request,'registration/registration.html')
            else:
                user_obj = user_check[0]
                user_obj.set_password(pwd1)
                user_obj.is_superuser = True
                user_obj.save()
                return HttpResponseRedirect(reverse('login'))
    return render(request,'registration/registration.html')

class createpost(CreateView,LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'blogapp/post_detail.html'
    model = Post
    template_name = 'blogapp/createpost.html'
    form_class = PostForm

    def post(self,request):
        postform = PostForm(self.request.POST)
        if postform.is_valid():
            post_obj = postform.save(commit=False)
            post_obj.author = request.user
            if 'submit_post' in self.request.POST:
                post_obj.publish()
            else:
                post_obj.save()
        return HttpResponseRedirect(reverse('blogapp:post_list'))

class draft_list(ListView,LoginRequiredMixin):
    redirect_field_name = 'blogapp/home.html'
    model = Post
    context_object_name = 'post_list'
    template_name='blogapp/draft_list.html'
    def get_queryset(self):
        return Post.objects.filter(published_date__isnull = True).filter(author=self.request.user).order_by('-id')

class post_list(ListView,LoginRequiredMixin):
    redirect_field_name = 'blogapp/post_list.html'
    model = Post
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.filter(published_date__lte = timezone.now()).order_by('-id')

class PostDetail(DetailView,LoginRequiredMixin):
    redirect_field_name = 'blogapp/post_detail.html'
    model = Post

class DraftDetail(DetailView,LoginRequiredMixin):
    redirect_field_name = 'blogapp/home.html'
    model = Post
    template_name='blogapp/draft_detail.html'

class UpdatePost(UpdateView,LoginRequiredMixin):
    redirect_field_name = 'blogapp/post_detail.html'
    model = Post
    template_name = 'blogapp/editpost.html'
    form_class = PostForm

    def get(self,request,pk):
        if Post.objects.get(id=pk).author != self.request.user:
            return HttpResponseRedirect(reverse('blogapp:post_list'))
        return super().get(request,pk)


class PostDelete(DeleteView,LoginRequiredMixin):
    redirect_field_name = 'blogapp/deleteconfirm.html'
    model = Post
    success_url = reverse_lazy('blogapp:post_list')
    template_name = 'blogapp/deleteconfirm.html'
    def get(self,request,pk):
        if Post.objects.get(id=pk).author != self.request.user:
            return HttpResponseRedirect(reverse('blogapp:post_list'))
        return super().get(request,pk)

@login_required
def editcomment(request,cid):
    txt = request.POST.get('comment_text')
    com_obj = Comment.objects.get(id=cid)
    pid = com_obj.post.id
    com_obj.text = txt
    com_obj.save()
    return HttpResponseRedirect(reverse('blogapp:post_detail',kwargs={'pk':pid}))

@login_required
def delete_comment(request,cid):
    com_obj = Comment.objects.get(id=cid)
    pid = com_obj.post.id
    com_obj.delete()
    return HttpResponseRedirect(reverse('blogapp:post_detail',kwargs={'pk':pid}))

@login_required
def draftpost(request, pid):
    if request.method == 'POST':
        post = Post.objects.get(id=pid)
        if 'draft_delete' in request.POST:
            post.delete()
            return HttpResponseRedirect(reverse('blogapp:post_list'))
        else:
            d_title = request.POST.get('draft_title')
            d_text = request.POST.get('draft_text')
            post.text = d_text
            post.title = d_title
            post.publish()
        return HttpResponseRedirect(reverse('blogapp:post_detail',kwargs={'pk':pid}))

@login_required
def CreateComment(request, cid):
    if request.method == 'GET':
        return HttpResponseRedirect(reverse('blogapp:post_detail',kwargs={'pk':cid}))
    if request.method == 'POST':
        comment_author = request.user
        comment_text = request.POST.get('comment')
        comment_post = Post.objects.get(id=cid)
        com_obj = Comment.objects.get_or_create(post=comment_post,text=comment_text,author=comment_author)
        if com_obj[1] == True:
            com_obj[0].save()
        return HttpResponseRedirect(reverse('blogapp:post_detail',kwargs={'pk':cid}))

blogapp/templates/blogapp/base.html
<!DOCTYPE html>
<!-- {% load static %} -->
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>
    {% block nameblock %}
    {% endblock %}
  </title>
  <style>
  #fortext{
    height: 50%;
  }
  .bd-title {
      font-size: calc(1.425rem + 2.1vw);
      margin-left: 50px;
      padding: 20px;
      padding-left: 0px;
  }

  .bd-label{
    font-size: 2.1rem;
  }

  </style>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blogapp:post_list' %}">Posts</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">LogOut</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blogapp:createpost' %}">Create Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blogapp:draft_list' %}">Drafts</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

  <div class="container-fluid">
    {% if user.is_authenticated %}

    <div class="row">
      <div class="col">
        {% block title_block %}
        {% endblock %}
      </div>
      <div class="col">
        <h6 class="text-end me-5 mt-4" style="padding:20px; padding-left:0px;" >Hello, {{user.username}}</h6>
      </div>
    </div>
    {% endif %}
    {% block bodyblock %}
    {% endblock %}
  </div>
</body>
</html>

blogapp/templates/blogapp/createpost.html
{% extends 'blogapp/base.html' %}
{% block nameblock %}
Create Post
{% endblock %}
{% block title_block %}
<h1 class = 'bd-title'>Create Post</h1>
{% endblock %}
{% block bodyblock %}
<!-- {{form.title}} -->
<form method="post">
  {% csrf_token %}
  <div class="form-floating m-5 mt-2 mb-0">
  {{form.as_p}}
  </div>

  <input type="submit" name='submit_post' class="btn btn-primary mt-2 ms-5 me-2" value="Submit">
  <input type="submit" name='draft_post' class="btn btn-secondary mt-2 mx-2" value="Draft">
  <a class="btn btn-danger mt-2 mx-2" href='{% url 'blogapp:post_list' %}'>Cancel</a>
</form>


{% endblock %}

blogapp/templates/blogapp/deleteconfirm.html
{% extends "blogapp/base.html" %}
{% block nameblock %}
Delete Post
{% endblock %}
{% block title_block %}
<h1 class = 'bd-title'>Delete Post</h1>
{% endblock %}
{% block bodyblock %}
  <form class='m-5 mt-2' method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete ?</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
    <a class='btn btn-info' href="{% url 'blogapp:post_list' %}">Cancel</a>
  </form>
{% endblock %}

blogapp/templates/blogapp/draft_detail.html
{% extends 'blogapp/base.html' %}
{% block nameblock %}
Draft Post
{% endblock %}
{% block title_block %}
<h1 class = 'bd-title'>Draft Post</h1>
{% endblock %}

{% block bodyblock %}

<div class="card m-5 mt-3 mb-3">
  <div class="card-header">
    <strong class='ms-2'>{{post.author}}</strong>
  </div>
  <div class="card-body">

<form action="{% url 'blogapp:draft_post' pid=post.id %}" method="post">
  {% csrf_token %}
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">Title</label>
      <input type="text" name='draft_title' class="form-control" id="exampleFormControlInput1" value='{{post.title}}'>
    </div>
    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">Text</label>
      <textarea class="form-control" name='draft_text' id="exampleFormControlTextarea1" rows="3">{{post.text}}</textarea>
    </div>

<input type="submit" name='draft_submit' class='btn btn-primary me-3' value="Submit">
<input type="submit" name='draft_delete' class='btn btn-danger' value="Delete">
</form>
  </div>
</div>

{% endblock %}

blogapp/templates/blogapp/draft_list.html
{% extends 'blogapp/base.html' %}
{% block nameblock %}
Draft Post
{% endblock %}
{% block title_block %}
<h1 class = 'bd-title'>Draft Posts</h1>
{% endblock %}
{% block bodyblock %}

{% for post in post_list %}
<div class="card m-5 mt-3 mb-3">
  <div class="card-header">
        <strong class="col ms-2">{{post.author}}</strong>
  </div>
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
    <p class="card-text">{{post.text|safe|truncatewords:"50"|linebreaks}}</p>
    <a class='stretched-link' href="{% url 'blogapp:draft_detail' pk=post.id %}"></a>
  </div>
</div>
{% endfor %}
{% endblock %}

blogapp/templates/blogapp/editpost.html
{% extends 'blogapp/base.html' %}
{% block nameblock %}
Edit Post
{% endblock %}
{% block title_block %}
<h1 class = 'bd-title'>Edit Post</h1>
{% endblock %}
{% block bodyblock %}

<form class="m-5 mt-2" method="post">
  {% csrf_token %}
    <label for="fortitle" class="form-label bd-label">Title</label>
    {{form.title}}
    <label for="fortext" class="form-label bd-label">Text</label>
    {{form.text}}
  <input type="submit" class="btn btn-primary mt-2" value="Submit">
</form>

{% endblock %}

blogapp/templates/blogapp/home.html
{% extends 'blogapp/base.html' %}
{% block nameblock %}
Home
{% endblock %}

{% if user.is_authenticated %}
{% block title_block %}
<h1 class = 'bd-title'>Welcome!</h1>
{% endblock %}
{% endif %}


{% block bodyblock %}

{% if not user.is_authenticated %}
<div class="text-sm-center p-5 bg-light">
  <h1>Home Page</h1>
</div>

{% else %}

{% if post_list.count == 0 %}
<p class='bd-label' style="margin-left:50px;">You do not have any posts yet!</p>
{% else %}
<p class='bd-label' style="margin-left:50px;">Your Posts</p>
{% endif %}
{% for post in post_list %}
<div class="card m-5 mt-3 mb-3">
  <div class="card-header">
    <div class="row">
      <div class="col ms-2">
        <strong>{{post.author}}</strong>
      </div>
      <div class="col">
        <div class="text-end me-5"><small>{{ post.published_date|date:"D, d M Y h:i A"}}</small></div>
      </div>
    </div>
  </div>
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
    <p class="card-text">{{post.text|safe|truncatewords:"50"|linebreaks}}</p>
    <a class='stretched-link' href="{% url 'blogapp:post_detail' pk=post.id %}"></a>
  </div>
</div>
{% endfor %}
{% endif %}
{% endblock %}

blogapp/templates/blogapp/post_detail.html
{% extends 'blogapp/base.html' %}
{% block title_block %}
<h1 class = 'bd-title'>Post Detail Page</h1>
{% endblock %}
{% block nameblock %}
Post Detail Page
{% endblock %}

{% block bodyblock %}
<div class="card m-5 mt-3 mb-3">
  <div class="card-header">
    <div class="row">
      <div class="col ms-2">
        <strong>{{post.author}}</strong>
      </div>
      <div class="col">
        <div class="text-end me-5">
          <small>{{ post.published_date|date:"D, d M Y h:i A"}}</small>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
    <p class="card-text">{{post.text}}</p>
  </div>
</div>
<div class="m-5 mb-0 mt-3">
  {% if post.author == user %}
  <a class='btn btn-sm btn-primary' href='{% url "blogapp:editpost" pk=post.id %}'>Edit Post</a>
  <a class='btn btn-sm btn-danger' href='{% url "blogapp:deletepost" pk=post.id %}'>Delete Post</a>
  {% endif %}
  <button onclick="myFunction()" class='btn btn-secondary btn-sm'>
    <i class="material-icons" style='vertical-align:center; font-size:1em;'>add</i>Add Comment
  </button>
</div>

<div id="commentdiv" style='display:none'>
  <h6 class='m-5 mt-3 mb-0' style='font-size:1.5rem'> Add Comment</h6>
  <form action="{% url 'blogapp:comment' cid=post.id %}" method="post">
    {% csrf_token %}

    <div class="container overflow-hidden m-5 mt-3 mb-0">
      <div class="row gx-5">
      <div class="col-md-10">
        <label for="exampleFormControlTextarea1" class="form-label">Comment</label>
        <textarea class="form-control" name='comment' id="exampleFormControlTextarea1" rows="3"></textarea>
      </div>
    </div>
    <input type="submit" class="btn btn-primary btn-sm mt-3" value="Add Comment">
  </div>

</form>
</div>

<h1 class = 'bd-label m-5 mt-3 mb-0'>Comments</h1>
{% if post.comments.count != 0 %}
{% for comment in post.comments.all %}
<div id='vanish_edit_{{comment.id}}'>

  <div class="card m-5 mt-3 mb-0">
    <div class="card-body">
      <p class="card-text">{{comment.text}}</p>

      <div class="row">
        <div class="col-sm-2">
          <h6 class="card-title">{{comment.author}}</h6>
        </div>


        {% if user == comment.author or  user == post.author%}
        <div class="col-sm-1">
          <button class='btn btn-outline-secondary btn-sm' onclick="vanishFunction({{comment.id}})">Edit</button>
        </div>

        <form class="col-sm-1" action="{% url 'blogapp:delete_comment' cid=comment.id %}" method="post">
          {% csrf_token %}
          <button class='btn btn-outline-danger btn-sm' type="submit">Delete</button>
        </form>
        {% endif %}

      </div>
    </div>
  </div>

</div>
<div id="appear_edit_{{comment.id}}" style="display:none">
  <div class="card m-5 mt-3 mb-0">
    <div class="card-body">

      <form action="{% url 'blogapp:edit_comment' cid=comment.id %}" method="post">
        {% csrf_token %}
        <div class="form-floating">
          <textarea class="form-control" name='comment_text' id="floatingTextarea">{{comment.text}}</textarea>
          <label for="floatingTextarea">Edit Comment</label>
        </div>

        <div class="row mt-3">
          <div class="col-sm-2">
            <h6 class="card-title">{{comment.author}}</h6>
          </div>


          <div class="col-sm-1">
            <button class='btn btn-outline-secondary btn-sm' type="submit">Update</button>
          </div>


          <div class="col-sm-1">
            <a class='btn btn-outline-danger btn-sm' href="javascript:location.reload(true)">Cancel</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endfor %}
{% else %}
<div class="text-sm-center p-5 bg-light m-5 mt-0">
  <small>No Comments</small>
</div>
{% endif %}


<script>
  function myFunction() {
    var x = document.getElementById("commentdiv");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }

  function vanishFunction(comment_id) {
    var x = document.getElementById("vanish_edit_"+comment_id);
    x.style.display = "none";
    var y = document.getElementById("appear_edit_"+comment_id);
    y.style.display = "block";
  }

</script>
{% endblock %}

blogapp/templates/blogapp/post_list.html
{% extends 'blogapp/base.html' %}
{% block nameblock %}
Posts
{% endblock %}
{% block title_block %}
<h1 class = 'bd-title'>Posts</h1>
{% endblock %}
{% block bodyblock %}

{% for post in post_list %}
<div class="card m-5 mt-3 mb-3">
  <div class="card-header">

    <div class="row">
      <div class="col ms-2">
        <strong>{{post.author}}</strong>
      </div>
      <div class="col">
        <div class="text-end me-5">
          <small>{{ post.published_date|date:"D, d M Y h:i A"}}</small>
        </div>
      </div>
    </div>

  </div>
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
    <p class="card-text">{{post.text|safe|truncatewords:"50"|linebreaks}}</p>
    <a class='stretched-link' href="{% url 'blogapp:post_detail' pk=post.id %}"></a>
  </div>
</div>
{% endfor %}
{% endblock %}